### ISSUE TITLE
Pulling me out of cars

### ISSUE THREAD

**Issue by Gizmo804** [XxModZxXWiiPlaza/Dog-Emotes-#1]
so when im driving if i let go of W or the left stick it pulls me out of the vehicle. not sure whats causing this and its tied to this code

**Comment by HearingSubset19** [comment]
@Gizmo804 :) #2 

or comment out lines 237-244
![image](https://user-images.githubusercontent.com/45643254/150737071-4ae80787-1d12-4cc9-a030-625707eb0ea2.png)

**Comment by XxModZxXWiiPlaza** [comment]
Merged with main repo. Didn’t realize this script would be used so much. Maybe I’ll rework it to make it better. Thanks for the issue fix.
